/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassBooking {
  'serviceType' : ServiceType,
  'date' : string,
  'name' : string,
  'email' : string,
  'preferredTimeSlot' : TimeSlot,
  'message' : string,
  'phone' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface MembershipInquiry {
  'name' : string,
  'email' : string,
  'preferredPlan' : MembershipPlan,
  'phone' : string,
}
export type MembershipPlan = { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'halfYearly' : null } |
  { 'yearly' : null };
export interface NewsletterSignup {
  'name' : string,
  'email' : string,
  'timestamp' : Time,
}
export type ServiceType = { 'weightTraining' : null } |
  { 'personalTraining' : null } |
  { 'zumba' : null } |
  { 'cardio' : null } |
  { 'nutrition' : null };
export type Time = bigint;
export type TimeSlot = { 'morning' : null } |
  { 'evening' : null } |
  { 'afternoon' : null };
export interface _SERVICE {
  'getAllClassBookings' : ActorMethod<[], Array<ClassBooking>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllMembershipInquiries' : ActorMethod<[], Array<MembershipInquiry>>,
  'getAllNewsletterSignups' : ActorMethod<[], Array<NewsletterSignup>>,
  'getClassBooking' : ActorMethod<[string], ClassBooking>,
  'getContactSubmission' : ActorMethod<[string], ContactSubmission>,
  'getMembershipInquiry' : ActorMethod<[string], MembershipInquiry>,
  'getNewsletterSignup' : ActorMethod<[string], NewsletterSignup>,
  'submitClassBooking' : ActorMethod<
    [string, string, string, ServiceType, TimeSlot, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitMembershipInquiry' : ActorMethod<
    [string, string, string, MembershipPlan],
    undefined
  >,
  'submitNewsletterSignup' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];