/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'weightTraining' : IDL.Null,
  'personalTraining' : IDL.Null,
  'zumba' : IDL.Null,
  'cardio' : IDL.Null,
  'nutrition' : IDL.Null,
});
export const TimeSlot = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const ClassBooking = IDL.Record({
  'serviceType' : ServiceType,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredTimeSlot' : TimeSlot,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const MembershipPlan = IDL.Variant({
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
  'halfYearly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const MembershipInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredPlan' : MembershipPlan,
  'phone' : IDL.Text,
});
export const NewsletterSignup = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllMembershipInquiries' : IDL.Func(
      [],
      [IDL.Vec(MembershipInquiry)],
      ['query'],
    ),
  'getAllNewsletterSignups' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSignup)],
      ['query'],
    ),
  'getClassBooking' : IDL.Func([IDL.Text], [ClassBooking], ['query']),
  'getContactSubmission' : IDL.Func([IDL.Text], [ContactSubmission], ['query']),
  'getMembershipInquiry' : IDL.Func([IDL.Text], [MembershipInquiry], ['query']),
  'getNewsletterSignup' : IDL.Func([IDL.Text], [NewsletterSignup], ['query']),
  'submitClassBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, TimeSlot, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitMembershipInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, MembershipPlan],
      [],
      [],
    ),
  'submitNewsletterSignup' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'weightTraining' : IDL.Null,
    'personalTraining' : IDL.Null,
    'zumba' : IDL.Null,
    'cardio' : IDL.Null,
    'nutrition' : IDL.Null,
  });
  const TimeSlot = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const ClassBooking = IDL.Record({
    'serviceType' : ServiceType,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredTimeSlot' : TimeSlot,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const MembershipPlan = IDL.Variant({
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
    'halfYearly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const MembershipInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredPlan' : MembershipPlan,
    'phone' : IDL.Text,
  });
  const NewsletterSignup = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAllClassBookings' : IDL.Func([], [IDL.Vec(ClassBooking)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllMembershipInquiries' : IDL.Func(
        [],
        [IDL.Vec(MembershipInquiry)],
        ['query'],
      ),
    'getAllNewsletterSignups' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSignup)],
        ['query'],
      ),
    'getClassBooking' : IDL.Func([IDL.Text], [ClassBooking], ['query']),
    'getContactSubmission' : IDL.Func(
        [IDL.Text],
        [ContactSubmission],
        ['query'],
      ),
    'getMembershipInquiry' : IDL.Func(
        [IDL.Text],
        [MembershipInquiry],
        ['query'],
      ),
    'getNewsletterSignup' : IDL.Func([IDL.Text], [NewsletterSignup], ['query']),
    'submitClassBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ServiceType,
          TimeSlot,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitMembershipInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, MembershipPlan],
        [],
        [],
      ),
    'submitNewsletterSignup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };