/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface ClassBooking {
    serviceType: ServiceType;
    date: string;
    name: string;
    email: string;
    preferredTimeSlot: TimeSlot;
    message: string;
    phone: string;
}
export interface NewsletterSignup {
    name: string;
    email: string;
    timestamp: Time;
}
export interface MembershipInquiry {
    name: string;
    email: string;
    preferredPlan: MembershipPlan;
    phone: string;
}
export enum MembershipPlan {
    quarterly = "quarterly",
    monthly = "monthly",
    halfYearly = "halfYearly",
    yearly = "yearly"
}
export enum ServiceType {
    weightTraining = "weightTraining",
    personalTraining = "personalTraining",
    zumba = "zumba",
    cardio = "cardio",
    nutrition = "nutrition"
}
export enum TimeSlot {
    morning = "morning",
    evening = "evening",
    afternoon = "afternoon"
}
export interface backendInterface {
    getAllClassBookings(): Promise<Array<ClassBooking>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllMembershipInquiries(): Promise<Array<MembershipInquiry>>;
    getAllNewsletterSignups(): Promise<Array<NewsletterSignup>>;
    getClassBooking(email: string): Promise<ClassBooking>;
    getContactSubmission(email: string): Promise<ContactSubmission>;
    getMembershipInquiry(email: string): Promise<MembershipInquiry>;
    getNewsletterSignup(email: string): Promise<NewsletterSignup>;
    submitClassBooking(name: string, email: string, phone: string, serviceType: ServiceType, preferredTimeSlot: TimeSlot, date: string, message: string): Promise<void>;
    submitContactForm(name: string, email: string, phone: string, message: string): Promise<void>;
    submitMembershipInquiry(name: string, email: string, phone: string, preferredPlan: MembershipPlan): Promise<void>;
    submitNewsletterSignup(name: string, email: string): Promise<void>;
}
import type { ClassBooking as _ClassBooking, MembershipInquiry as _MembershipInquiry, MembershipPlan as _MembershipPlan, ServiceType as _ServiceType, TimeSlot as _TimeSlot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllClassBookings(): Promise<Array<ClassBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClassBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClassBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllMembershipInquiries(): Promise<Array<MembershipInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipInquiries();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipInquiries();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsletterSignups(): Promise<Array<NewsletterSignup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsletterSignups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsletterSignups();
            return result;
        }
    }
    async getClassBooking(arg0: string): Promise<ClassBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassBooking(arg0);
                return from_candid_ClassBooking_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassBooking(arg0);
            return from_candid_ClassBooking_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmission(arg0: string): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmission(arg0);
            return result;
        }
    }
    async getMembershipInquiry(arg0: string): Promise<MembershipInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipInquiry(arg0);
                return from_candid_MembershipInquiry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipInquiry(arg0);
            return from_candid_MembershipInquiry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsletterSignup(arg0: string): Promise<NewsletterSignup> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsletterSignup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsletterSignup(arg0);
            return result;
        }
    }
    async submitClassBooking(arg0: string, arg1: string, arg2: string, arg3: ServiceType, arg4: TimeSlot, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClassBooking(arg0, arg1, arg2, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg3), to_candid_TimeSlot_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClassBooking(arg0, arg1, arg2, to_candid_ServiceType_n13(this._uploadFile, this._downloadFile, arg3), to_candid_TimeSlot_n15(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitMembershipInquiry(arg0: string, arg1: string, arg2: string, arg3: MembershipPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMembershipInquiry(arg0, arg1, arg2, to_candid_MembershipPlan_n17(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMembershipInquiry(arg0, arg1, arg2, to_candid_MembershipPlan_n17(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitNewsletterSignup(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitNewsletterSignup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitNewsletterSignup(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ClassBooking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassBooking): ClassBooking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipInquiry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipInquiry): MembershipInquiry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipPlan_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipPlan): MembershipPlan {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TimeSlot_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeSlot): TimeSlot {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    preferredPlan: _MembershipPlan;
    phone: string;
}): {
    name: string;
    email: string;
    preferredPlan: MembershipPlan;
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        preferredPlan: from_candid_MembershipPlan_n11(_uploadFile, _downloadFile, value.preferredPlan),
        phone: value.phone
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: _ServiceType;
    date: string;
    name: string;
    email: string;
    preferredTimeSlot: _TimeSlot;
    message: string;
    phone: string;
}): {
    serviceType: ServiceType;
    date: string;
    name: string;
    email: string;
    preferredTimeSlot: TimeSlot;
    message: string;
    phone: string;
} {
    return {
        serviceType: from_candid_ServiceType_n4(_uploadFile, _downloadFile, value.serviceType),
        date: value.date,
        name: value.name,
        email: value.email,
        preferredTimeSlot: from_candid_TimeSlot_n6(_uploadFile, _downloadFile, value.preferredTimeSlot),
        message: value.message,
        phone: value.phone
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    yearly: null;
}): MembershipPlan {
    return "quarterly" in value ? MembershipPlan.quarterly : "monthly" in value ? MembershipPlan.monthly : "halfYearly" in value ? MembershipPlan.halfYearly : "yearly" in value ? MembershipPlan.yearly : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weightTraining: null;
} | {
    personalTraining: null;
} | {
    zumba: null;
} | {
    cardio: null;
} | {
    nutrition: null;
}): ServiceType {
    return "weightTraining" in value ? ServiceType.weightTraining : "personalTraining" in value ? ServiceType.personalTraining : "zumba" in value ? ServiceType.zumba : "cardio" in value ? ServiceType.cardio : "nutrition" in value ? ServiceType.nutrition : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
}): TimeSlot {
    return "morning" in value ? TimeSlot.morning : "evening" in value ? TimeSlot.evening : "afternoon" in value ? TimeSlot.afternoon : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassBooking>): Array<ClassBooking> {
    return value.map((x)=>from_candid_ClassBooking_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipInquiry>): Array<MembershipInquiry> {
    return value.map((x)=>from_candid_MembershipInquiry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_MembershipPlan_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipPlan): _MembershipPlan {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TimeSlot_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): _TimeSlot {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    weightTraining: null;
} | {
    personalTraining: null;
} | {
    zumba: null;
} | {
    cardio: null;
} | {
    nutrition: null;
} {
    return value == ServiceType.weightTraining ? {
        weightTraining: null
    } : value == ServiceType.personalTraining ? {
        personalTraining: null
    } : value == ServiceType.zumba ? {
        zumba: null
    } : value == ServiceType.cardio ? {
        cardio: null
    } : value == ServiceType.nutrition ? {
        nutrition: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeSlot): {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
} {
    return value == TimeSlot.morning ? {
        morning: null
    } : value == TimeSlot.evening ? {
        evening: null
    } : value == TimeSlot.afternoon ? {
        afternoon: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipPlan): {
    quarterly: null;
} | {
    monthly: null;
} | {
    halfYearly: null;
} | {
    yearly: null;
} {
    return value == MembershipPlan.quarterly ? {
        quarterly: null
    } : value == MembershipPlan.monthly ? {
        monthly: null
    } : value == MembershipPlan.halfYearly ? {
        halfYearly: null
    } : value == MembershipPlan.yearly ? {
        yearly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
